version: '3.7'

services:
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
  salt-minion-centos7:
    build:
      context: .
      dockerfile: Dockerfile.minion.centos7
    depends_on:
      - salt-master
  salt-minion-centos8:
    build:
      context: .
      dockerfile: Dockerfile.minion.centos8
    depends_on:
      - salt-master
  salt-minion-ubuntu1804:
    build:
      context: .
      dockerfile: Dockerfile.minion.ubuntu1804
    depends_on:
      - salt-master
  salt-minion-opensuse:
    build:
      context: .
      dockerfile: Dockerfile.minion.opensuse.leap15
    depends_on:
      - salt-master
