FROM centos:7
MAINTAINER tim@cyface.com

RUN yum install -y --nogpgcheck epel-release && \
    yum install -y --nogpgcheck https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el7.noarch.rpm && \
    yum clean expire-cache && \
    yum update -y && \
    yum install -y virt-what salt-minion && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN sed -i "s|#master: salt|master: salt-master|g" /etc/salt/minion

ENTRYPOINT ["salt-minion", "-l", "debug"]

